Update XHlive.yml

diff --git a/.github/workflows/XHlive.yml b/.github/workflows/XHlive.yml
--- a/.github/workflows/XHlive.yml
+++ b/.github/workflows/XHlive.yml
@@ -26,17 +26,18 @@ jobs:
         with:
           fetch-depth: 0 # 获取所有历史记录，以便比较
 
-      - name: Check for new commits
-        id: check_commits
+      - name: Check New Commit
         run: |
-          LAST_SUCCESSFUL_BUILD_SHA=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?branch=${{ github.ref }}&event=schedule" | jq -r '.workflow_runs[0].head_sha')
-          CURRENT_HEAD_SHA=$(git rev-parse HEAD)
-          if [ "$CURRENT_HEAD_SHA" == "$LAST_SUCCESSFUL_BUILD_SHA" ]; then
-            echo "No new commits since last successful build."
+          upStream="https://github.com/xisohi/XHlive"
+          echo "upStream=$upStream" >> $GITHUB_ENV
+          commit=$(curl -sL "https://api.github.com/repos/xisohi/XHlive/commits/main" | jq -r '.sha')
+          if [ $? -ne 0 ]; then
+            echo "Failed to get commit from API"
             exit 1
-          else
-            echo "New commits found."
-            echo "last_commit=$LAST_SUCCESSFUL_BUILD_SHA" >> $GITHUB_ENV
+          fi
+          if [ -z "$commit" ] || ! grep -q "$commit" README.md; then
+            echo "commit=$commit" >> $GITHUB_ENV
+            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
           fi
 
       - name: Generate Tag Name
@@ -47,40 +48,34 @@ jobs:
           VERSION_CODE="$(date +'%y%m%d%H')"
           echo "version_code=$VERSION_CODE" >> $GITHUB_ENV
 
-#      - name: Update version
-#        id: update_version
-#        id: update_version
-#        run: |
-#          sed -i "s/\"version_code\": [0-9]*/\"version_code\": ${{ env.version_code }}/" version.json
-#          sed -i "s/\"version_name\": \"v[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\"/\"version_name\": \"${{ env.tag_name }}\"/" version.json
+      - name: Update version
+        id: update_version
+        run: |
+          sed -i "s/\"version_code\": [0-9]*/\"version_code\": ${{ env.version_code }}/" version.json
+          sed -i "s/\"version_name\": \"v[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\"/\"version_name\": \"${{ env.tag_name }}\"/" version.json
 
-#      - name: Commit and push version.json changes
-#        run: |
-#          git config --local user.email "action@github.com"
-#          git config --local user.name "GitHub Action"
-#          git add version.json
-#          git commit -m "Update version.json"
-#          git push
+      - name: Commit and push version.json changes
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add version.json
+          git commit -m "Update version.json"
+          git push
 
-#      - name: Get the new commit SHA after version update
-#        id: get_new_commit_sha
-#        run: |
-#          NEW_COMMIT_SHA=$(git rev-parse HEAD)
-#          echo "new_commit_sha=$NEW_COMMIT_SHA" >> $GITHUB_ENV
 
-#      - name: Recheck for new commits after version update
-#        if: steps.get_new_commit_sha.outcome == 'success'
-#        id: recheck_commits_after_update
-#        run: |
-#          LAST_SUCCESSFUL_BUILD_SHA=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?branch=${{ github.ref }}&event=schedule" | jq -r '.workflow_runs[0].head_sha')
-#          NEW_COMMIT_SHA=${{ env.new_commit_sha }}
-#          if [ "$LAST_SUCCESSFUL_BUILD_SHA" == "$NEW_COMMIT_SHA" ]; then
-#            echo "No new commits since last successful build."
-#            exit 1
-#          else
-#            echo "New commits found."
-#            echo "last_commit=$LAST_SUCCESSFUL_BUILD_SHA" >> $GITHUB_ENV
-#          fi
+      - name: Recheck New Commit
+        run: |
+          upStream="https://github.com/xisohi/XHlive"
+          echo "upStream=$upStream" >> $GITHUB_ENV
+          commit=$(curl -sL "https://api.github.com/repos/xisohi/XHlive/commits/main" | jq -r '.sha')
+          if [ $? -ne 0 ]; then
+            echo "Failed to get commit from API"
+            exit 1
+          fi
+          if [ -z "$commit" ] || ! grep -q "$commit" README.md; then
+            echo "commit=$commit" >> $GITHUB_ENV
+            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
+          fi
 
       - name: Create Tag
         if: steps.recheck_commits_after_update.outcome == 'success'
