修改更新路径

diff --git a/.github/workflows/XHlive.yml b/.github/workflows/XHlive.yml
--- a/.github/workflows/XHlive.yml
+++ b/.github/workflows/XHlive.yml
@@ -34,32 +34,23 @@ jobs:
           fetch-depth: 0 # 获取所有历史记录，以便比较
 
       - name: Check New Commit
-        id: check_commit
         run: |
-          last_commit=$(git log -1 --format='%H')
-          echo "Last commit on last run: $last_commit"
-          latest_commit=$(curl -sL "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.sha')
-          echo "Latest commit from API: $latest_commit"
-          if [ "$latest_commit" != "$last_commit" ]; then
-            echo "New commit detected. Proceeding with further steps..."
-            echo "run_steps=true" >> $GITHUB_ENV
-          else
-            echo "No new commit."
-            echo "run_steps=false" >> $GITHUB_ENV
-            exit 0
+          upStream="https://github.com/${{ matrix.userName }}/${{ matrix.repoName }}"
+          echo "upStream=$upStream" >> $GITHUB_ENV
+          commit=$(curl -sL "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.sha')
+          if [ $? -ne 0 ]; then
+            echo "Failed to get commit from API"
+            exit 1
           fi
-
-      - name: Check if commit is in Releases
-        if: ${{ env.run_steps == 'true' }}
-        run: |
-          commit_hash=${{ steps.check_commit.outputs.latest_commit }}
-          release_list=$(curl -s "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/releases")
-          if echo "$release_list" | grep -q "\"sha\": \"$commit_hash\""; then
-            echo "Commit is already in Releases. Exiting workflow."
-            exit 0
-          else
-            echo "Commit is not in Releases. Continuing workflow."
+          # 从update分支获取sn.md文件的内容
+          git fetch origin update:temp
+          tempSnMdContent=$(git show origin/update:sn.md)
+          if [ -z "$commit" ] || ! echo "$tempSnMdContent" | grep -q "$commit"; then
+            echo "commit=$commit" >> $GITHUB_ENV
+            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
           fi
+          # 清理临时分支
+          git branch -D temp
 
       - name: Generate Tag Name
         if: ${{ env.run_steps == 'true' }}
